---
hostname: NACNBCLSVP03
local_bgp_asn: 64854
azure_bgp_asn: 10000
colo_loopback0: 10.137.68.30
#configure loopback for each vrf
loopback_interfaces:
  loopback675:
    loop_ipv4: 10.137.68.21
    loop_vrf: AVIATRIX-UNDERLAY
    description: "AVIATRIX-UNDERLAY loopback interface"
  loopback676:
    loop_ipv4: 10.137.68.22
    loop_vrf: AVIATRIX-UNDERLAY-QDL
    description: "AVIATRIX-UNDERLAY loopback interface for preprod-QA-Lab"
# portchannel setup
int_port_channel:
  Po1:
    id: 1
  Po2:
    id: 2  
# configure layer 3 interfaces
layer_interfaces:
  Te0/0/0:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/1:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/2:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/3:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/8:
    status: "no shut"
    description: "description connection to colo switch NACNBCLSW02 E1/28"
    lacp: present
    lacp_id: 2
  Te0/0/9:
    status: "no shut"
    description: "description connection to colo switch NACBCLSW02 E1/27"
    lacp: present
    lacp_id: 2
  Te0/0/10:
    status: "no shut"
    description: "description connection to colo switch NACNBCLSW02 E1/26"
    lacp: present
    lacp_id: 2
  Te0/0/11:
    status: "no shut"
    description: "description connection to colo switch NACBCLSW02 E1/25"
    lacp: present
    lacp_id: 2
sub_interfaces:
  Po1.677:
    description: "<insert description here>"
    vrf: AZCP21
    dot1q: 677
    ipv4_add: "<add azure ip address>"
  Po2.675:
    description: "connection to NACNBCLSW02 Po2 VRF AVIATRIX-UNDERLAY"
    vrf: AVIATRIX-UNDERLAY
    dot1q: 675
    ipv4_add: 10.137.64.122
  Po2.676:
    description: "connection to NACNBCLSW02 Po2 VRF AVIATRIX-UNDERLAY-QDL"
    vrf: AVIATRIX-UNDERLAY-QDL
    dot1q: 676
    ipv4_add: 10.137.64.186
router_bgp:
  xroute_peer1:
    remote_bgp_ipv4_address: 1.2.3.1
    description: "BGP to Azure Expressroute VRF AZCP21"
    remote_bgp_asn: 10000
    vrf: AVIATRIX-UNDERLAY
  xroute_peer2:
    remote_bgp_ipv4_address: 1.2.3.1
    description: "BGP to Azure Expressroute VRF AZCP21"
    remote_bgp_asn: 10000
    vrf: AVIATRIX-UNDERLAY-QDL
  colosw2_peer1:
    remote_bgp_ipv4_address: 10.137.64.121
    description: "BGP to Colo Switch NACNBCLSW01 VRF AZCD21"
    remote_bgp_asn: 64919
    vrf: AVIATRIX-UNDERLAY
  colosw1_peer2:
    remote_bgp_ipv4_address: 10.137.64.185
    description: "BGP to Colo Switch NACNBCLSW01 VRF AVIATRIX-UNDERLAY-QDL"
    remote_bgp_asn: 64919
    vrf: AVIATRIX-UNDERLAY-QDL