---
  hostname: nacnbclvp01
  loopback0: 10.137.68.27 
  local_bgp_asn: 65188
# define vrfs
  vrf_definition:
    vrf_azcl21:
      vrf_name: AZCL21
      vrf_dot1q: 674
    vrf_azcd21:
      vrf_name: AZCD21
      vrf_dot1q: 675
    vrf_azcq21:
      vrf_name: AZCQ21
      vrf_dot1q: 676
    vrf_azcp21:
      vrf_name: AZCP21
      vrf_dot1q: 677
    vrf_azcl21-fvrf:
      vrf_name: AZCL21-FVRF
      vrf_dot1q: 1674
    vrf_azcd21-fvrf:
      vrf_name: AZCD21-FVRF
      vrf_dot1q: 1675
    vrf_azcq21-fvrf:
      vrf_name: AZCQ21-FVRF
      vrf_dot1q: 1676
    vrf_azcp21-fvrf:
      vrf_name: AZCP21-FVRF
      vrf_dot1q: 1677
# define port-channel interfaces
  po_int:
    po_1:
      id: 1
      description: "port-channel to vp02"
    po_2:
      id: 2  
      description: "port-channel to sw01"
#  define l3 interface 
  l3_interfaces:
    Te0/0/4:
      description: "connection to nacnbclvp02 Te0/0/4"
      lacp: present
    Te0/0/5:
      description: "connection to nacnbclvp02 Te0/0/5"
      lacp: present
    Te0/0/0:
      description: "connection to nacnbclsw01 E1/13"
      lacp: present
    Te0/0/1:
      description: "connection to nacnbclsw01 E1/14"  
      lacp: present
    Te0/0/11:
      description: "connection to ncdznbclvp01 Te0/0/11"
      lacp: absent
    Te0/0/10:
      description: "connection to ntdzbclvp01 Te0/0/10"
      lacp: absent
# define loopback interface 
  loopback_interfaces:
    loop674:
      loop_vrf: AZCL21
      loop_ipv4: 10.137.68.41
      loop_description: "vrf azcl21 loopback interface"
    loop675:
      loop_vrf: AZCD21
      loop_ipv4: 10.137.68.8
      loop_description: "vrf azcp21 loopback interface"
    loop676:
      loop_vrf: AZCQ21
      loop_ipv4: 10.137.68.9
      loop_description: "vrf azcp21 loopback interface"
    loop677:
      loop_vrf: AZCP21
      loop_ipv4: 10.137.68.7
      loop_description: "vrf azcp21 loopback interface"
  layer3_sub_int:
    Po2.674:
      dot1q: 674
      ipv4_add: 10.137.64.118
      vrf : AZCL21
      description: " L3 connnection to nacnbclsw01 Po11.674"
    Po2.675:
      dot1q: 675
      ipv4_add: 10.137.64.73
      vrf : AZCD21
      description: " L3 connnection to nacnbclsw01 Po11.675"
    Po2.676:
      dot1q: 676
      ipv4_add: 10.137.64.137
      vrf : AZCQ21
      description: " L3 connnection to nacnbclsw01 Po11.676"
    Po2.677:
      dot1q: 677
      ipv4_add: 10.137.64.9
      vrf : AZCP21
      description: " L3 connnection to nacnbclsw01 Po11.677"
    Po1.674:
      dot1q: 674
      ipv4_add: 10.137.64.113
      vrf : AZCL21
      description: " L3 connnection to nacnbclvp02 Po1.674"
    Po1.675:
      dot1q: 675
      ipv4_add: 10.137.64.89
      vrf : AZCD21
      description: " L3 connnection to nacnbclvp02 Po1.675"
    Po1.676:
      dot1q: 676
      ipv4_add: 10.137.64.153
      vrf : AZCQ21
      description: " L3 connnection to nacnbclvp02 Po1.675"
    Po1.677:
      dot1q: 677
      ipv4_add: 10.137.64.25
      vrf : AZCP21
      description: " L3 connnection to nacnbclvp02 Po1.675"
    Te0/0/11.674:
      dot1q: 674
      ipv4_add: 10.137.64.177
      vrf : AZCL21-FVRF
      description: " L3 connnection to ncdzbclvp01 Te0/0/11.674"
    Te0/0/11.675:
      dot1q: 675
      ipv4_add: 10.137.64.209
      vrf : AZCD21-FVRF
      description: " L3 connnection to ncdzbclvp01 Te0/0/11.675"
    Te0/0/11.676:
      dot1q: 676
      ipv4_add: 10.137.64.225
      vrf : AZCQ21-FVRF
      description: " L3 connnection to ncdzbclvp01 Te0/0/11.676"
    Te0/0/11.677:
      dot1q: 677
      ipv4_add: 10.137.64.1
      vrf : AZCP21-FVRF
      description: " L3 connnection to ncdzbclvp01 Te0/0/11.677"
    Te0/0/10.674:
      dot1q: 674
      ipv4_add: 10.137.64.181 
      vrf : AZCL21-FVRF
      description: " L3 connnection to ntdzbclvp01 Te0/0/10.674"
    Te0/0/10.675:
      dot1q: 675
      ipv4_add: 10.137.64.217 
      vrf : AZCD21-FVRF
      description: " L3 connnection to ntdzbclvp01 Te0/0/10.675"
    Te0/0/10.676:
      dot1q: 676
      ipv4_add: 10.137.64.233
      vrf : AZCQ21-FVRF
      description: " L3 connnection to ntdzbclvp01 Te0/0/10.676"
    Te0/0/10.677:
      dot1q: 677
      ipv4_add: 10.136.64.201
      vrf : AZCP21-FVRF
      description: " L3 connnection to ntdzbclvp01 Te0/0/10.677"
  vti_tunnel_interfaces:
    tunnel674:
      vrf: AZCL21
      ipv4: 10.137.65.1
      src: 10.137.64.177
      dest: 10.137.64.178
      desc: "vti tunnel to ncdzbclvp01 tunnel 674"
      fvrf: AZCL21-FVRF 
    tunnel675:
      vrf: AZCD21
      ipv4: 10.137.64.93
      src: 10.137.64.209
      dest: 10.137.64.210
      desc: "vti tunnel to ncdzbclvp01 tunnel 675"
      fvrf: AZCD21-FVRF 
    tunnel676:
      vrf: AZCQ21
      ipv4: 10.137.64.157
      src: 10.137.64.225
      dest: 10.137.64.226
      desc: "vti tunnel to ncdzbclvp01 tunnel 676"
      fvrf: AZCQ21-FVRF
    tunnel677:
      vrf: AZCP21
      ipv4: 10.137.64.29 
      src: 10.137.64.1
      dest: 10.137.64.2
      desc: "vti tunnel to ncdzbclvp01 tunnel 677"
      fvrf: AZCP21-FVRF
    tunnel1674:
      vrf: AZCL21
      ipv4: 10.137.65.5
      src: 10.137.64.181
      dest: 10.137.64.182
      desc: "vti tunnel to ntdzbclvp01 tunnel 1674"
      fvrf: AZCL21-FVRF 
    tunnel1675:
      vrf: AZCD21
      ipv4: 10.137.64.101
      src: 10.137.64.217
      dest: 10.137.64.218
      desc: "vti tunnel to ntdzbclvp01 tunnel 1675"
      fvrf: AZCD21-FVRF
    tunnel1676:
      vrf: AZCQ21
      ipv4: 10.137.64.165 
      src: 10.137.64.233
      dest: 10.137.64.234
      desc: "vti tunnel to ntdzbclvp01 tunnel 1676"
      fvrf: AZCQ21-FVRF
    tunnel1677:
      vrf: AZCP21
      ipv4: 10.137.64.37
      src: 10.137.64.201
      dest: 10.137.64.202
      desc: "vti tunnel to ntdzbclvp01 tunnel 1677"
      fvrf: AZCP21-FVRF
  bgp_neighbors:
    sw01peer1:
      remote_asn: 64919
      remote_ipv4: 10.137.64.74
      bgp_type: ebgp
      bgp_vrf: AZCD21
      desc: "bgp peer to nacnbclsw01 vrf azcd21"
    sw01peer2:
      remote_asn: 64919
      remote_ipv4: 10.137.64.138
      bgp_type: ebgp
      bgp_vrf: AZCQ21
      desc: "bgp peer to nacnbclsw01 vrf azcq21"
    sw01peer3:
      remote_asn: 64919
      remote_ipv4: 10.137.64.10
      bgp_type: ebgp
      bgp_vrf: AZCP21
      desc: "bgp peer to nacnbclsw01 vrf azcp21"
    sw01peer4:
      remote_asn: 64919
      remote_ipv4: 10.137.64.117
      bgp_type: ebgp
      bgp_vrf: AZCL21
      desc: "bgp peer to nacnbclsw01 vrf azcl21"
    colo_vp02peer1:
      remote_asn: 65188
      remote_ipv4: 10.137.64.90
      bgp_type: ibgp
      bgp_vrf: AZCD21
      desc: "bgp peer to nacnbclv001 vrf azcd21"
    colo_vp02peer2:
      remote_asn: 65188
      remote_ipv4: 10.137.64.154
      bgp_type: ibgp
      bgp_vrf: AZCQ21
      desc: "bgp peer to nacnbclv001 vrf azcq21"
    colo_vp02peer3:
      remote_asn: 65188
      remote_ipv4: 10.137.64.26
      bgp_type: ibgp
      bgp_vrf: AZCP21
      desc: "bgp peer to nacnbclv001 vrf azcp21"
    colo_vp02peer4:
      remote_asn: 65188
      remote_ipv4: 10.137.64.114
      bgp_type: ibgp
      bgp_vrf: AZCL21
      desc: "bgp peer to nacnbclv001 vrf azcl21"
    ncd_vp01peer1:
      remote_asn: 64805
      remote_ipv4: 10.137.64.94
      bgp_type: ebgp
      bgp_vrf: AZCD21
      desc: "bgp peer to ncdzbclvp01 vrf azcd21"
    ncd_vp01peer2:
      remote_asn: 64805
      remote_ipv4: 10.137.64.158
      bgp_type: ebgp
      bgp_vrf: AZCQ21
      desc: "bgp peer to ncdzbclvp01 vrf azcq21"
    ncd_vp01peer3:
      remote_asn: 64805
      remote_ipv4: 10.137.64.30
      bgp_type: ebgp
      bgp_vrf: AZCP21
      desc: "bgp peer to ncdzbclvp01 vrf azcp21"
    ncd_vp01peer4:
      remote_asn: 64805
      remote_ipv4: 10.137.65.2
      bgp_type: ebgp
      bgp_vrf: AZCL21
      desc: "bgp peer to ncdzbclvp01 vrf azcl21"
    ntd_vp01peer1:
      remote_asn: 64526
      remote_ipv4: 10.137.64.102
      bgp_type: ebgp
      bgp_vrf: AZCD21
      desc: "bgp peer to ntdzbclvp01 vrf azcd21"
    ntd_vp01peer2:
      remote_asn: 64526
      remote_ipv4: 10.137.64.166
      bgp_type: ebgp
      bgp_vrf: AZCQ21
      desc: "bgp peer to ntdzbclvp01 vrf azcq21"
    ntd_vp01peer3:
      remote_asn: 64526
      remote_ipv4: 10.137.64.38
      bgp_type: ebgp
      bgp_vrf: AZCP21
      desc: "bgp peer to ntdzbclvp01 vrf azcp21"
    ntd_vp01peer4:
      remote_asn: 64526
      remote_ipv4: 10.137.65.6
      bgp_type: ebgp
      bgp_vrf: AZCL21
      desc: "bgp peer to ntdzbclvp01 vrf azcl21"
  ikev2_policy:
      fvrf1: AZCD21-FVRF
      fvrf2: AZCQ21-FVRF
      fvrf3: AZCP21-FVRF
      fvrf4: AZCL21-FVRF
