---
  hostname: nacnbclvp02
  loopback0: 10.137.68.28
  local_bgp_asn: 65188
# define vrfs
  vrf_definition:
    vrf_azcl21:
      vrf_name: AZCL21
      vrf_dot1q: 674
    vrf_azcd21:
      vrf_name: AZCD21
      vrf_dot1q: 675
    vrf_azcq21:
      vrf_name: AZCQ21
      vrf_dot1q: 676
    vrf_azcp21:
      vrf_name: AZCP21
      vrf_dot1q: 677
    vrf_azcl21-fvrf:
      vrf_name: AZCL21-FVRF
      vrf_dot1q: 1674
    vrf_azcd21-fvrf:
      vrf_name: AZCD21-FVRF
      vrf_dot1q: 1675
    vrf_azcq21-fvrf:
      vrf_name: AZCQ21-FVRF
      vrf_dot1q: 1676
    vrf_azcp21-fvrf:
      vrf_name: AZCP21-FVRF
      vrf_dot1q: 1677
# define port-channel interfaces
  po_int:
    po_1:
      id: 1
      description: "port-channel to vp01"
    po_2:
      id: 2  
      description: "port-channel to sw02"
#  define l3 interface 
  l3_interfaces:
    Te0/0/4:
      description: "connection to nacnbclvp02 Te0/0/4"
      lacp: present
    Te0/0/5:
      description: "connection to nacnbclvp02 Te0/0/5"
      lacp: present
    T0/0/1:
      description: "connection to nacnbclsw02 E1/13"
      lacp: absent
    Te0/0/1:
      description: "connection to nacnbclsw01 E1/14"
      lacp: absent
    Te0/0/11:
      description: "connection to ncdznbclvp02 Te0/0/11"
      lacp: absent
    Te0/0/10:
      description: "connection to ntdzbclvp02 Te0/0/10"
      lacp: absent
# define loopback interface 
  loopback_interfaces:
    loop674:
      loop_vrf: AZCL21
      loop_ipv4: 10.137.68.42
      loop_description: "vrf azcl21 loopback interface"
    loop675:
      loop_vrf: AZCD21
      loop_ipv4: 10.137.68.11
      loop_description: "vrf azcp21 loopback interface"
    loop676:
      loop_vrf: AZCQ21
      loop_ipv4: 10.137.68.12
      loop_description: "vrf azcp21 loopback interface"
    loop677:
      loop_vrf: AZCP21
      loop_ipv4: 10.137.68.10
      loop_description: "vrf azcp21 loopback interface"
  layer3_sub_int:
    Po2.674:
      dot1q: 674
      ipv4_add: 10.137.64.50
      vrf : AZCL21
      description: " L3 connnection to nacnbclsw01 Po11.674"
    po2.675:
      dot1q: 675
      ipv4_add: 10.137.64.85
      vrf : AZCD21
      description: " L3 connnection to nacnbclsw02 Po11.675"
    po2.676:
      dot1q: 676
      ipv4_add: 10.137.64.149
      vrf : AZCQ21
      description: " L3 connnection to nacnbclsw02 Po11.676"
    po2.677:
      dot1q: 677
      ipv4_add: 10.137.64.21
      vrf : AZCP21
      description: " L3 connnection to nacnbclsw02 Po11.677"
    Po1.674:
      dot1q: 674
      ipv4_add: 10.137.64.114
      vrf : AZCL21
      description: " L3 connnection to nacnbclvp01 Po1.674"
    Po1.675:
      dot1q: 675
      ipv4_add: 10.137.64.90
      vrf : AZCD21
      description: " L3 connnection to nacnbclvp01 Po1.675"
    Po1.676:
      dot1q: 676
      ipv4_add: 10.137.64.154
      vrf : AZCQ21
      description: " L3 connnection to nacnbclvp01 Po1.676"
    Po1.677:
      dot1q: 677
      ipv4_add: 10.137.64.26
      vrf : AZCP21
      description: " L3 connnection to nacnbclvp01 Po1.677"
    Te0/0/11.674:
      dot1q: 674
      ipv4_add: 10.137.65.17
      vrf : AZCDL1-FVRF
      description: " L3 connnection to ncdzbclvp02 Te0/0/11.674"
    Te0/0/11.675:
      dot1q: 675
      ipv4_add: 10.137.64.213
      vrf : AZCD21-FVRF
      description: " L3 connnection to ncdzbclvp02 Te0/0/11.675"
    Te0/0/11.676:
      dot1q: 676
      ipv4_add: 10.137.64.229
      vrf : AZCQ21-FVRF
      description: " L3 connnection to ncdzbclvp02 Te0/0/11.676"
    Te0/0/11.677:
      dot1q: 677
      ipv4_add: 10.137.64.5
      vrf : AZCP21-FVRF
      description: " L3 connnection to ncdzbclvp02 Te0/0/11.677"
    Te0/0/10.674:
      dot1q: 674
      ipv4_add: 10.137.65.21
      vrf : AZCL21-FVRF
      description: " L3 connnection to ntdzbclvp02 Te0/0/10.674"
    Te0/0/10.675:
      dot1q: 675
      ipv4_add: 10.137.64.221 
      vrf : AZCD21-FVRF
      description: " L3 connnection to ntdzbclvp02 Te0/0/10.675"
    Te0/0/10.676:
      dot1q: 676
      ipv4_add: 10.137.64.237
      vrf : AZCQ21-FVRF
      description: " L3 connnection to ntdzbclvp02 Te0/0/10.676"
    Te0/0/10.677:
      dot1q: 677
      ipv4_add: 10.137.64.205
      vrf : AZCP21-FVRF
      description: " L3 connnection to ntdzbclvp02 Te0/0/10.677"
  vti_tunnel_interfaces:
    tunnel674:
      vrf: AZCL21
      ipv4: 10.137.65.9
      src: 10.137.65.17
      dest: 10.137.65.18
      desc: 
      fvrf: AZCL21-FVRF 
    tunnel675:
      vrf: AZCD21
      ipv4: 10.137.64.97
      src: 10.137.64.213
      dest: 10.137.64.214
      desc: 
      fvrf: AZCD21-FVRF 
    tunnel676:
      vrf: AZCQ21
      ipv4: 10.137.64.161
      src: 10.137.64.229
      dest: 10.137.64.230
      desc: 
      fvrf: AZCQ21-FVRF
    tunnel677:
      vrf: AZCP21
      ipv4: 10.137.64.33  
      src: 10.137.64.5
      dest: 10.137.64.6
      desc: 
      fvrf: AZCP21-FVRF
    tunnel1674:
      vrf: AZCL21
      ipv4: 10.137.65.13
      src: 10.137.65.21
      dest: 10.137.65.22
      desc: 
      fvrf: AZCL21-FVRF 
    tunnel1675:
      vrf: AZCD21
      ipv4: 10.137.64.105
      src: 10.137.64.221
      dest: 10.137.64.222
      desc: 
      fvrf: AZCD21-FVRF
    tunnel1676:
      vrf: AZCQ21
      ipv4: 10.137.64.169 
      src: 10.137.64.237
      dest: 10.137.64.238
      desc: 
      fvrf: AZCQ21-FVRF
    tunnel1677:
      vrf: AZCP21
      ipv4: 10.137.64.41
      src: 10.137.64.205
      dest: 10.137.64.206
      desc: 
      fvrf: AZCP21-FVRF
  bgp_neighbors:
    sw02peer1:
      remote_asn: 64919
      remote_ipv4: 10.137.64.86
      bgp_type: ebgp
      bgp_vrf: AZCD21
    sw02peer2:
      remote_asn: 64919
      remote_ipv4: 10.137.64.150
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    sw02peer3:
      remote_asn: 64919
      remote_ipv4: 10.137.64.22
      bgp_type: ebgp
      bgp_vrf: AZCP21
    sw02peer4:
      remote_asn: 64919
      remote_ipv4: 10.137.64.49
      bgp_type: ebgp
      bgp_vrf: AZCL21
    colo_vp01peer1:
      remote_asn: 65188
      remote_ipv4: 10.137.64.89
      bgp_type: ibgp
      bgp_vrf: AZCD21
    colo_vp01peer2:
      remote_asn: 65188
      remote_ipv4: 10.137.64.153
      bgp_type: ibgp
      bgp_vrf: AZCQ21 
    colo_vp01peer3:
      remote_asn: 65188
      remote_ipv4: 10.137.64.25
      bgp_type: ibgp
      bgp_vrf: AZCP21
    colo_vp01peer4:
      remote_asn: 65188
      remote_ipv4: 10.137.64.113
      bgp_type: ibgp
      bgp_vrf: AZCL21
    ncd_vp02peer1:
      remote_asn: 64805
      remote_ipv4: 10.137.64.98
      bgp_type: ebgp
      bgp_vrf: AZCD21
    ncd_vp02peer2:
      remote_asn: 64805
      remote_ipv4: 10.137.64.162
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    ncd_vp02peer3:
      remote_asn: 64805
      remote_ipv4: 10.137.64.34
      bgp_type: ebgp
      bgp_vrf: AZCP21
    ncd_vp02peer4:
      remote_asn: 64805
      remote_ipv4: 10.137.66.10
      bgp_type: ebgp
      bgp_vrf: AZCL21
    ntd_vp02peer1:
      remote_asn: 64526
      remote_ipv4: 10.137.64.106
      bgp_type: ebgp
      bgp_vrf: AZCD21
    ntd_vp02peer2:
      remote_asn: 64526
      remote_ipv4: 10.137.64.170
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    ntd_vp02peer3:
      remote_asn: 64526
      remote_ipv4: 10.137.64.42
      bgp_type: ebgp
      bgp_vrf: AZCP21
    ntd_vp02peer4:
      remote_asn: 64526
      remote_ipv4: 10.137.65.14
      bgp_type: ebgp
      bgp_vrf: AZCL21
  ikev2_policy:
      fvrf1: AZCD21-FVRF
      fvrf2: AZCQ21-FVRF
      fvrf3: AZCP21-FVRF
      fvrf4: AZCL21-FVRF
