---
local_bgp_asn: 64854
hostname: dc11_vp04
azure_bgp_asn: 10000
colo_loopback0: 10.137.68.30
#configure loopback for each vrf
loopback_interfaces:
  loopback677:
    loop_ipv4: 10.137.68.22
    loop_vrf: AZCP21
    description: "AZCP21 loopback interface"
  loopback676:
    loop_ipv4: 10.137.68.23
    loop_vrf: AZCQ21
    description: "AZCP21 loopback interface"
  loopback675:
    loop_ipv4: 10.137.68.21
    loop_vrf: AZCD21
    description: "AZCP21 loopback interface"
# portchannel setup
int_port_channel:
  Po1:
    id: 1
  Po2:
    id: 2  
# configure layer 3 interfaces
layer_interfaces:
  Te0/0/0:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/1:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/2:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/3:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/8:
    status: "no shut"
    description: "description connection to colo switch NACNBCLSW02 E1/28"
    lacp: present
    lacp_id: 2
  Te0/0/9:
    status: "no shut"
    description: "description connection to colo switch NACBCLSW02 E1/27"
    lacp: present
    lacp_id: 2
  Te0/0/10:
    status: "no shut"
    description: "description connection to colo switch NACNBCLSW02 E1/26"
    lacp: present
    lacp_id: 2
  Te0/0/11:
    status: "no shut"
    description: "description connection to colo switch NACBCLSW02 E1/25"
    lacp: present
    lacp_id: 2
  sub_interfaces:
  Po1.677:
    description: "<insert description here>"
    vrf: AZCP21
    dot1q: 677
    ipv4_add: "<add azure ip address>"
  Po1.676:
    description: "<insert description here>"
    vrf: AZCQ21
    dot1q: 676
    ipv4_add: "<add azure ip address>"
  Po1.675:
    description: "<insert description here>"
    vrf: AZCD21
    dot1q: 675
    ipv4_add: "<add azure ip address>"
  Po2.677:
    description: "<connection to NACNBCLSW02 E1/45 VRF AZCP21"
    vrf: AZCP21
    dot1q: 677
    ipv4_add: 10.137.64.58
  Po2.676:
    description: "<connection to NACNBCLSW02 E1/45 VRF AZCQ21"
    vrf: AZCQ21
    dot1q: 676
    ipv4_add: 10.137.64.186
  Po2.675:
    description: "<connection to NACNBCLSW02 E1/45 VRF AZCQ21"
    vrf: AZCD21
    dot1q: 675
    ipv4_add: 10.137.64.122
router_bgp:
  azure_peer1:
    remote_bgp_ipv4_address: 1.2.3.1
    description: "BGP to Azure Expressroute VRF AZCP21"
    remote_bgp_asn: "<AZURE BGP ASN>"
    vrf: AZCP21
  azure_peer2:
    remote_bgp_ipv4_address: 1.2.3.4
    description: "BGP to Azure Expressroute VRF AZCD21"
    remote_bgp_asn: "<AZURE BGP ASN"
    vrf: AZCD21
  azure_peer3:
    remote_bgp_ipv4_address: 1.2.3.4
    description: "BGP to Azure Expressroute VRF AZCQ21"
    remote_bgp_asn: "<AZURE BGP ASN"
    vrf: AZCQ21
  sw02_peer1:
    remote_bgp_ipv4_address: 10.137.64.57
    description: "BGP to Colo Switch NACNBCLSW02 VRF AZCP21"
    remote_bgp_asn: 64919
    vrf: AZCP21
  sw02_peer2:
    remote_bgp_ipv4_address: 10.137.64.121
    description: "BGP to Colo Switch NACNBCLSW02 VRF AZCD21"
    remote_bgp_asn: 64919
    vrf: AZCD21
  sw02_peer3:
    remote_bgp_ipv4_address: 10.137.64.185
    description: "BGP to Colo Switch NACNBCLSW02 VRF AZCQ21"
    remote_bgp_asn: 64919
    vrf: AZCQ21