---
  hostname: ncd_vp02
  loopback0: 10.137.68.32
  local_bgp_asn: 12345
# define vrfs
  vrf_definition:
    vrf_azcd21:
      vrf_name: AZCD21
      vrf_dot1q: 675
    vrf_azcq21:
      vrf_name: AZCQ21
      vrf_dot1q: 676
    vrf_azcp21:
      vrf_name: AZCP21
      vrf_dot1q: 677
    vrf_azcd21-fvrf:
      vrf_name: AZCD21-FVRF
      vrf_dot1q: 1675
    vrf_azcq21-fvrf:
      vrf_name: AZCQ21-FVRF
      vrf_dot1q: 1676
    vrf_azcp21-fvrf:
      vrf_name: AZCP21-FVRF
      vrf_dot1q: 1677
#  define l3 interface 
  l3_interfaces:
    GigabitEthernet1:
      description: "connection to xyz"
    GigabitEthernet2:
      description: "connection to xyz"
    GigabitEthernet4:
      description: "connection to xyz"
# define loopback interface 
  loopback_interfaces:
    loop675:
      loop_vrf: AZCD21
      loop_ipv4: 10.137.68.14
      loop_description: "vrf azcp21 loopback interface"
    loop676:
      loop_vrf: AZCQ21
      loop_ipv4: 10.137.68.15
      loop_description: "vrf azcp21 loopback interface"
    loop677:
      loop_vrf: AZCP21
      loop_ipv4: 10.137.68.13
      loop_description: "vrf azcp21 loopback interface"
  layer3_sub_int:
    GigabitEthernet2.675:
      dot1q: 675
      ipv4_add: 10.137.64.74
      vrf : AZCD21
      description:
    GigabitEthernet2.676:
      dot1q: 676
      ipv4_add: 10.137.64.138
      vrf : AZCQ21
      description:
    GigabitEthernet2.677:
      dot1q: 677
      ipv4_add: 10.137.64.10
      vrf : AZCP21
      description: 
    GigabitEthernet1.675:
      dot1q: 675
      ipv4_add: 10.137.64.214
      vrf : AZCD21-FVRF
      description:
    GigabitEthernet1.676:
      dot1q: 676
      ipv4_add: 10.137.64.230
      vrf : AZCQ21-FVRF
      description:
    GigabitEthernet1.677:
      dot1q: 677
      ipv4_add: 10.137.64.6
      vrf : AZCP21-FVRF
      description:
    GigabitEthernet4.675:
      dot1q: 675
      ipv4_add: 10.137.80.222 
      vrf : AZCD21-FVRF
      description:
    GigabitEthernet4.676:
      dot1q: 676
      ipv4_add: 10.137.80.238
      vrf : AZCQ21-FVRF
      description:
    GigabitEthernet4.677:
      dot1q: 677
      ipv4_add: 10.136.80.206
      vrf : AZCP21-FVRF
      description:
  vti_tunnel_interfaces:
    tunnel675:
      vrf: AZCD21
      ipv4: 10.137.64.98
      src: 10.137.64.214
      dest: 10.137.64.213
      desc: 
      fvrf: AZCD21-FVRF 
    tunnel676:
      vrf: AZCQ21
      ipv4: 10.137.64.162 
      src: 10.137.64.230
      dest: 10.137.64.229
      desc: 
      fvrf: AZCQ21-FVRF
    tunnel677:
      vrf: AZCP21
      ipv4: 10.137.64.34 
      src: 10.137.64.6
      dest: 10.137.64.5
      desc: 
      fvrf: AZCP21-FVRF
    tunnel1675:
      vrf: AZCD21
      ipv4: 10.137.80.106
      src: 10.137.80.222
      dest: 10.137.80.221
      desc: 
      fvrf: AZCD21-FVRF
    tunnel1676:
      vrf: AZCQ21
      ipv4: 10.137.80.170 
      src: 10.137.80.238
      dest: 10.137.80.237
      desc: 
      fvrf: AZCQ21-FVRF
    tunnel1677:
      vrf: AZCP21
      ipv4: 10.137.80.42
      src: 10.137.80.206
      dest: 10.137.80.205
      desc: 
      fvrf: AZCP21-FVRF
  bgp_neighbors:
    dc11_colo_vp02peer1:
      remote_asn: 65188
      remote_ipv4: 10.137.64.97
      bgp_type: ebgp
      bgp_vrf: AZCD21
    dc11_colo_vp02peer2:
      remote_asn: 65188
      remote_ipv4: 10.137.64.161
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    dc11_colo_vp02peer3:
      remote_asn: 65188
      remote_ipv4: 10.137.64.33
      bgp_type: ebgp
      bgp_vrf: AZCP21
    da3_vp02peer1:
      remote_asn: 65206
      remote_ipv4: 10.137.80.105
      bgp_type: ebgp
      bgp_vrf: AZCD21
    da3_vp02peer2:
      remote_asn: 65206
      remote_ipv4: 10.137.80.169
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    da3_vp02peer3:
      remote_asn: 65206
      remote_ipv4: 10.137.80.41
      bgp_type: ebgp
      bgp_vrf: AZCP21
    ncd_vp02peer1:
      remote_asn: 12345
      remote_ipv4: 10.137.64.73
      bgp_type: ibgp
      bgp_vrf: AZCD21
    ncd_vp02peer2:
      remote_asn: 12345
      remote_ipv4: 10.137.64.137
      bgp_type: ibgp
      bgp_vrf: AZCQ21 
    ncd_vp02peer3:
      remote_asn: 12345
      remote_ipv4: 10.137.64.9
      bgp_type: ibgp
      bgp_vrf: AZCP21
  ikev2_policy:
      fvrf1: AZCD21-FVRF
      fvrf2: AZCQ21-FVRF
      fvrf3: AZCP21-FVRF
