---
local_bgp_asn: 65190
colo_vp03_04_asn: 65189
colo_vp_01_02_asn: 65206
local_vpc_peer_ipv4: 10.137.80.253
remote_vpc_peer_ipv4: 10.137.80.254
loopback0: 10.137.84.25/32
loopback_interfaces:
  loop674:
    loop_ipv4: 10.137.84.39/32
    loop_description: " vrf AZCD21 loopback for testing"
    loop_vrf: AZCL21
  loop675:
    loop_ipv4: 10.137.84.2/32
    loop_description: " vrf AZCD21 loopback for testing"
    loop_vrf: AZCD21
  loop676:
    loop_ipv4: 10.137.84.3/32
    loop_description: " vrf AZCQ21 loopback for testing"
    loop_vrf: AZCQ21
  loop677:
    loop_ipv4: 10.137.84.1/32
    loop_description: " vrf AZCP21 loopback for testing"
    loop_vrf: AZCP21
  loop175:
    loop_ipv4: 10.137.84.33/32
    loop_description: " vrf AVIATRIX-UNDERLAY loopback for testing"
    loop_vrf: AVIATRIX-UNDERLAY
  loop176:
    loop_ipv4: 10.137.84.34/32
    loop_description: " vrf AVIATRIX-UNDERLAY-QDL loopback for testing"
    loop_vrf: AVIATRIX-UNDERLAY-QDL
vlan_interfaces:
  po1_674:
    vlan_id: 674
    vlan_ipv4: 10.137.80.53/30
    vlan_description: "ibgp for vrf AZCL21"
    vrf: AZCL21
  Po1_675:
    vlan_id: 675
    vlan_ipv4: 10.137.80.125/30
    vlan_description: "ibgp vlan for vrf AZCD21"
    vrf: AZCD21
  Po1_676:
    vlan_id: 676
    vlan_ipv4: 10.137.80.189/30
    vlan_description: "ibgp vlan for vrf AZCQ21"
    vrf: AZCQ21
  Po1_677:
    vlan_id: 677
    vlan_ipv4: 10.137.80.61/30
    vlan_description: "ibgp vlan for vrf AZCP21"
    vrf: AZCP21
  Po1_1675:
    vlan_id: 1675
    vlan_ipv4: 10.137.80.241/30
    vlan_description: "ibgp vlan for vrf AVIATRIX-UNDERLAY"
    vrf: AVIATRIX-UNDERLAY
  po1_1676:
    vlan_id: 1676
    vlan_ipv4: 10.137.80.245/30
    vlan_description: "ibgp for vrf AVIATRIX-UNDERLAY-QDL"
    vrf: AVIATRIX-UNDERLAY-QDL
vpc_interfaces:
  Ethernet1:
    vpc_int_id: 1/53
    vpc_portchannel_id: 1
  Ethernet2:
    vpc_int_id: 1/54
    vpc_portchannel_id: 1
  Ethernet3:
    vpc_int_id: 1/25
    vpc_portchannel_id: 10
  Ethernet4:
    vpc_int_id: 1/26
    vpc_portchannel_id: 10
  Ethernet5:
    vpc_int_id: 1/27
    vpc_portchannel_id: 10
  Ethernet6:
    vpc_int_id: 1/28
    vpc_portchannel_id: 10
  Ethernet7:
    vpc_int_id: 1/13
    vpc_portchannel_id: 11
  Ethernet8:
    vpc_int_id: 1/14
    vpc_portchannel_id: 11
vpc_id:
  vpc_1:
    po_id: "1"
  vpc_10:
    po_id: "10"
  vpc_11:
    po_id: "11"
l3_interfaces:
  ethernet1/25:
    description: " l3 connection to NDCNBLVP03"
  ethernet1/26:
    description: " l3 connection to NDCNBLVP03"
  ethernet1/27:
    description: " l3 connection to NDCNBLVP03"
  ethernet1/28:
    description: " l3 connection to NDCNBLVP03"
  ethernet1/1:
    description: " l3 connection to PROD AVI-WAN"
  ethernet1/5:
    description: " l3 connection to PROD AVI-LAN"
  ethernet1/13:
    description: " l3 connection to NDCNBLVP01"
  ethernet1/14:
    description: " l3 connection to NDCNBLVP01"
  ethernet1/2:
    description: " l3 connection to PRE-PROD-QA-LAB AVI-WAN"
  ethernet1/6:
    description: " l3 connection to PRE-PROD-QA-LAB AVI-LAN"
l3_sub_interfaces:
  P10.675:
    l3_sub_int_vrf: AVIATRIX-UNDERLAY
    l3_sub_int_ipv4: 10.137.80.109/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to NDCNBLVP04 VRF AVIATRIX-UNDERLAY"
  P10.676:
    l3_sub_int_vrf: AVIATRIX-UNDERLAY-QDL
    l3_sub_int_ipv4: 10.137.80.173/30
    l3_sub_int_dot1q: 676
    l3_sub_description: "L3 sub-interface connection to NDCNBLVP04 VRF AVIATRIX-UNDERLAY-QDL"
  ethernet1/5.677:
    l3_sub_int_vrf: AZCP21
    l3_sub_int_ipv4: 10.137.82.17/30
    l3_sub_int_dot1q: 677
    l3_sub_description: "L3 sub-interface connection to AVI PROD LAN VRF AZCP21"
  Po11.674:
    l3_sub_int_vrf: AZCL21
    l3_sub_int_ipv4: 10.137.80.117/30
    l3_sub_int_dot1q: 674
    l3_sub_description: "L3 sub-interface connection to NDCNBCLVP01 VRF AZCL21"
  Po11.675:
    l3_sub_int_vrf: AZCD21
    l3_sub_int_ipv4: 10.137.80.74/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to NDCNBCLVP01 VRF AZCD21"
  Po11.676:
    l3_sub_int_vrf: AZCQ21
    l3_sub_int_ipv4: 10.137.80.138/30
    l3_sub_int_dot1q: 676
    l3_sub_description: "L3 sub-interface connection to NDCNBCLVP01 VRF AZCQ21"
  Po11.677:
    l3_sub_int_vrf: AZCP21
    l3_sub_int_ipv4: 10.137.80.10/30
    l3_sub_int_dot1q: 677
    l3_sub_description: "L3 sub-interface connection to NDCNBCLVP01 VRF AZCP21"
  ethernet1/1.675:
    l3_sub_int_vrf: AVIATRIX-UNDERLAY
    l3_sub_int_ipv4: 10.137.82.5/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to AVI PROD WAN VRF AVIATRIX-UNDERLAY"
  ethernet1/2.675:
    l3_sub_int_vrf: AVIATRIX-UNDERLAY
    l3_sub_int_ipv4: 10.137.82.57/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD WAN VRF AVIATRIX-UNDERLAY"
  ethernet1/6.674:
    l3_sub_int_vrf: AZCL21
    l3_sub_int_ipv4: 10.137.82.57/30
    l3_sub_int_dot1q: 674
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD LAN VRF AZCL21"
  ethernet1/6.675:
    l3_sub_int_vrf: AZCD21
    l3_sub_int_ipv4: 10.137.82.53/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD LAN VRF AZCD21"
  ethernet1/6.676:
    l3_sub_int_vrf: AZCQ21
    l3_sub_int_ipv4: 10.137.82.61/30
    l3_sub_int_dot1q: 676
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD LAN VRF AZCQ21"
  ethernet1/6.677:
    l3_sub_int_vrf: AZCP21
    l3_sub_int_ipv4: 10.137.82.69/30
    l3_sub_int_dot1q: 677
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD LAN VRF AZCP21"
l3_bgp_neighbors:
  sw02_peer1:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.62
    bgp_vrf: AZCP21  
  sw02_peer2:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.190
    bgp_vrf: AZCQ21
  sw02_peer3:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.126
    bgp_vrf: AZCD21
  sw02_peer4:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.242
    bgp_vrf: AVIATRIX-UNDERLAY
  sw02_peer5:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.246
    bgp_vrf: AVIATRIX-UNDERLAY-QDL
  sw02_peer6:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.54
    bgp_vrf: AZCL21
  vp03_peer1: 
    bgp_type: ebgp
    remote_asn: 65189
    remote_bgp_peer_ipv4: 10.137.80.110
    bgp_vrf: AVIATRIX-UNDERLAY
  vp03_peer2: 
    bgp_type: ebgp
    remote_asn: 65189
    remote_bgp_peer_ipv4: 10.137.80.174
    bgp_vrf: AVIATRIX-UNDERLAY-QDL
  vp01_peer1:
    bgp_type: ebgp
    remote_asn: 65206
    remote_bgp_peer_ipv4: 10.137.80.73
    bgp_vrf: AZCD21
  vp01_peer2:
    bgp_type: ebgp
    remote_asn: 65206
    remote_bgp_peer_ipv4: 10.137.80.9
    bgp_vrf: AZCP21 
  vp01_peer3:
    bgp_type: ebgp
    remote_asn: 65206
    remote_bgp_peer_ipv4: 10.137.80.137
    bgp_vrf: AZCQ21
  vp01_peer4:
    bgp_type: ebgp
    remote_asn: 65206
    remote_bgp_peer_ipv4: 10.137.80.118
    bgp_vrf: AZCL21
  aviprod_peer1:
    bgp_type: ebgp
    remote_asn: 64521
    remote_bgp_peer_ipv4: 10.137.82.18
    bgp_vrf: AZCP21
  avi_qdl_peer1:
    bgp_type: ebgp
    remote_asn: 64523
    remote_bgp_peer_ipv4: 10.137.82.54
    bgp_vrf: AZCD21
  avi_qdl_peer2:
    bgp_type: ebgp
    remote_asn: 64522
    remote_bgp_peer_ipv4: 10.137.82.62
    bgp_vrf: AZCQ21 
  avi_qdl_peer4:
    bgp_type: ebgp
    remote_asn: 64524
    remote_bgp_peer_ipv4: 10.137.82.78
    bgp_vrf: AZCL21
redis_connected:
  ethernet1/1.675:
    vrf: AVIATRIX-UNDERLAY
  ethernet1/2.675:
    vrf: AVIATRIX-UNDERLAY-QDL