---
  hostname: ndcnbclvp02
  loopback0: 10.137.84.28
  local_bgp_asn: 65206
# define vrfs
  vrf_definition:
    vrf_azcd21:
      vrf_name: AZCD21
      vrf_dot1q: 675
    vrf_azcq21:
      vrf_name: AZCQ21
      vrf_dot1q: 676
    vrf_azcp21:
      vrf_name: AZCP21
      vrf_dot1q: 677
    vrf_azcd21-fvrf:
      vrf_name: AZCD21-FVRF
      vrf_dot1q: 1675
    vrf_azcq21-fvrf:
      vrf_name: AZCQ21-FVRF
      vrf_dot1q: 1676
    vrf_azcp21-fvrf:
      vrf_name: AZCP21-FVRF
      vrf_dot1q: 1677
# define port-channel interfaces
  po_int:
    po_1:
      id: 1
      description: "port-channel to vp01"
    po_2:
      id: 2  
      description: "port-channel to sw02"
#  define l3 interface 
  l3_interfaces:
    Te0/0/4:
      description: "connection to ndcnbclvp01 Te0/0/4"
      lacp: present
    Te0/0/5:
      description: "connection to ndcnbclvp01 Te0/0/5"
      lacp: present
    T0/0/0:
      description: "connection to ndcnbclsw02 E1/13"
      lacp: absent
    Te0/0/1:
      description: "connection to ndcnbclsw02 E1/14"
      lacp: absent
    Te0/0/11:
      description: "connection to ntdznbclvp02 Te0/0/11"
      lacp: absent
    Te0/0/10:
      description: "connection to ncdzbclvp02 Te0/0/10"
      lacp: absent
# define loopback interface 
  loopback_interfaces:
    loop675:
      loop_vrf: AZCD21
      loop_ipv4: 10.137.84.11
      loop_description: "vrf azcp21 loopback interface"
    loop676:
      loop_vrf: AZCQ21
      loop_ipv4: 10.137.84.12
      loop_description: "vrf azcp21 loopback interface"
    loop677:
      loop_vrf: AZCP21
      loop_ipv4: 10.137.84.10
      loop_description: "vrf azcp21 loopback interface"
  layer3_sub_int:
    Po2.675:
      dot1q: 675
      ipv4_add: 10.137.80.85
      vrf : AZCD21
      description: " L3 connnection to ndcnbclsw02 Po2.675"
    Po2.676:
      dot1q: 676
      ipv4_add: 10.137.80.149
      vrf : AZCQ21
      description: " L3 connnection to ndcnbclsw02 Po2.676"
    Po2.677:
      dot1q: 677
      ipv4_add: 10.137.80.21
      vrf : AZCP21
      description: " L3 connnection to ndcnbclsw02 Po2.677"
    Po1.675:
      dot1q: 675
      ipv4_add: 10.137.80.90
      vrf : AZCD21
      description: " L3 connnection to ndcnbclvp01 Po1.675"
    Po1.676:
      dot1q: 676
      ipv4_add: 10.137.80.154
      vrf : AZCQ21
      description: " L3 connnection to ndcnbclvp01 Po1.676"
    Po1.677:
      dot1q: 677
      ipv4_add: 10.137.80.26
      vrf : AZCP21
      description: " L3 connnection to ndcnbclvp01 Po1.677"
    Te0/0/11.675:
      dot1q: 675
      ipv4_add: 10.137.64.213
      vrf : AZCD21-FVRF
      description: " L3 connnection to ntzbclvp02 Te0/0/11.675"
    Te0/0/11.676:
      dot1q: 676
      ipv4_add: 10.137.80.229
      vrf : AZCQ21-FVRF
      description: " L3 connnection to nctzbclvp02 Te0/0/11.676"
    Te0/0/11.677:
      dot1q: 677
      ipv4_add: 10.137.80.5
      vrf : AZCP21-FVRF
      description: " L3 connnection to ntzbclvp02 Te0/0/11.677"
    Te0/0/10.675:
      dot1q: 675
      ipv4_add: 10.137.80.221 
      vrf : AZCD21-FVRF
      description: " L3 connnection to ncdzbclvp02 Te0/0/10.675"
    Te0/0/10.676:
      dot1q: 676
      ipv4_add: 10.137.80.237
      vrf : AZCQ21-FVRF
      description: " L3 connnection to ncdzbclvp02 Te0/0/10.676"
    Te0/0/10.677:
      dot1q: 677
      ipv4_add: 10.137.80.205
      vrf : AZCP21-FVRF
      description: " L3 connnection to ncdzbclvp02 Te0/0/10.677"
  vti_tunnel_interfaces:
    tunnel675:
      vrf: AZCD21
      ipv4: 10.137.80.97
      src: 10.137.80.213
      dest: 10.137.80.214
      desc: 
      fvrf: AZCD21-FVRF 
    tunnel676:
      vrf: AZCQ21
      ipv4: 10.137.80.161
      src: 10.137.80.229
      dest: 10.137.80.230
      desc: 
      fvrf: AZCQ21-FVRF
    tunnel677:
      vrf: AZCP21
      ipv4: 10.137.80.33  
      src: 10.137.80.5
      dest: 10.137.80.6
      desc: 
      fvrf: AZCP21-FVRF
    tunnel1675:
      vrf: AZCD21
      ipv4: 10.137.80.105
      src: 10.137.80.221
      dest: 10.137.80.222
      desc: 
      fvrf: AZCD21-FVRF
    tunnel1676:
      vrf: AZCQ21
      ipv4: 10.137.80.169 
      src: 10.137.80.237
      dest: 10.137.80.238
      desc: 
      fvrf: AZCQ21-FVRF
    tunnel1677:
      vrf: AZCP21
      ipv4: 10.137.80.41
      src: 10.137.80.205
      dest: 10.137.80.206
      desc: 
      fvrf: AZCP21-FVRF
  bgp_neighbors:
    sw02peer1:
      remote_asn: 65190
      remote_ipv4: 10.137.80.86
      bgp_type: ebgp
      bgp_vrf: AZCD21
    sw02peer2:
      remote_asn: 65190
      remote_ipv4: 10.137.80.150
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    sw02peer3:
      remote_asn: 65190
      remote_ipv4: 10.137.80.22
      bgp_type: ebgp
      bgp_vrf: AZCP21
    colo_vp01peer1:
      remote_asn: 65206
      remote_ipv4: 10.137.80.89
      bgp_type: ibgp
      bgp_vrf: AZCD21
    colo_vp01peer2:
      remote_asn: 65206
      remote_ipv4: 10.137.80.153
      bgp_type: ibgp
      bgp_vrf: AZCQ21 
    colo_vp01peer3:
      remote_asn: 65206
      remote_ipv4: 10.137.80.25
      bgp_type: ibgp
      bgp_vrf: AZCP21
    ncd_vp02peer1:
      remote_asn: 64805
      remote_ipv4: 10.137.80.106
      bgp_type: ebgp
      bgp_vrf: AZCD21
    ncd_vp02peer2:
      remote_asn: 64805
      remote_ipv4: 10.137.80.170
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    ncd_vp02peer3:
      remote_asn: 64805
      remote_ipv4: 10.137.80.42
      bgp_type: ebgp
      bgp_vrf: AZCP21
    ntd_vp02peer1:
      remote_asn: 64526
      remote_ipv4: 10.137.80.98
      bgp_type: ebgp
      bgp_vrf: AZCD21
    ntd_vp02peer2:
      remote_asn: 64526
      remote_ipv4: 10.137.80.162
      bgp_type: ebgp
      bgp_vrf: AZCQ21 
    ntd_vp02peer3:
      remote_asn: 64526
      remote_ipv4: 10.137.80.34
      bgp_type: ebgp
      bgp_vrf: AZCP21
  ikev2_policy:
      fvrf1: AZCD21-FVRF
      fvrf2: AZCQ21-FVRF
      fvrf3: AZCP21-FVRF
