---
local_bgp_asn: 65189
hostname: ndcnbclvp04
azure_bgp_asn: 10000
colo_loopback0: 10.137.84.30
#configure loopback for each vrf
loopback_interfaces:
  loopback675:
    loop_ipv4: 10.137.84.21
    loop_vrf: AVIATRIX-UNDERLAY
    description: "AVIATRIX-UNDERLAY loopback interface"
# portchannel setup
int_port_channel:
  Po1:
    id: 1
  Po2:
    id: 2  
# configure layer 3 interfaces
layer_interfaces:
  Te0/0/0:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/1:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/3:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/4:
    status: "no shut"
    description: "description connection to azure expressconnect"
    lacp: present
    lacp_id: 1
  Te0/0/8:
    status: "no shut"
    description: "description connection to colo switch NACNBCLSW01 E1/28"  
    lacp: present
    lacp_id: 2
  Te0/0/9:
    status: "no shut"
    description: "description connection to colo switch NACNBCLSW02 E1/27"
    lacp: present
    lacp_id: 2
  Te0/0/10:
    status: "no shut"
    description: "description connection to colo switch NACNBCLSW01 E1/26"  
    lacp: present
    lacp_id: 2
  Te0/0/11:
    status: "no shut"
    description: "description connection to colo switch NACNBCLSW02 E1/25"
    lacp: present
    lacp_id: 2
sub_interfaces:
  Po1.677:
    description: "<insert description here>"
    vrf: AZCP21
    dot1q: 677
    ipv4_add: "<add azure ip address>"
  Po2.675:
    description: "<connection to NDCNBCLSW02 E1/45 VRF AVIATRIX-UNDERLAY"
    vrf: AVIATRIX-UNDERLAY
    dot1q: 675
    ipv4_add: 10.137.80.122
router_bgp:
  azure_peer1:
    remote_bgp_ipv4_address: 1.2.3.1
    description: "BGP to Azure Expressroute VRF AZCP21"
    remote_bgp_asn: "<AZURE BGP ASN>"
    vrf: AZCP21
  sw02_peer2:
    remote_bgp_ipv4_address: 10.137.80.121
    description: "BGP to Colo Switch NDCNBCLSW02 VRF AZCD21"
    remote_bgp_asn: 65190
    vrf: AVIATRIX-UNDERLAY