---
local_bgp_asn: 65190
colo_vp03_04_asn: 65189
colo_vp_01_02_asn: 65206
local_vpc_peer_ipv4: 10.137.80.254
remote_vpc_peer_ipv4: 10.137.80.253
loopback0: 10.137.84.26/32
loopback_interfaces:
  loop675:
    loop_ipv4: 10.137.84.5/32
    loop_description: " vrf AZCD21 loopback for testing"
    loop_vrf: AZCD21
  loop676:
    loop_ipv4: 10.137.84.6/32
    loop_description: " vrf AZCQ21 loopback for testing"
    loop_vrf: AZCQ21
  loop677:
    loop_ipv4: 10.137.84.4/32
    loop_description: " vrf AZCP21 loopback for testing"
    loop_vrf: AZCP21
  loop175:
    loop_ipv4: 10.137.84.34/32
    loop_description: " vrf AZCD21-OUT loopback for testing"
    loop_vrf: AVIATRIX-UNDERLAY  
vlan_interfaces:
  Po1_675:
    vlan_id: 675
    vlan_ipv4: 10.137.80.126/30
    vlan_description: "ibgp vlan for vrf AZCD21"
    vrf: AZCD21
  Po1_676:
    vlan_id: 676
    vlan_ipv4: 10.137.80.190/30
    vlan_description: "ibgp vlan for vrf AZCQ21"
    vrf: AZCQ21
  Po1_677:
    vlan_id: 677
    vlan_ipv4: 10.137.80.62/30
    vlan_description: "ibgp vlan for vrf AZCP21"
    vrf: AZCP21
  Po1_1675:
    vlan_id: 1675
    vlan_ipv4: 10.137.80.242/30
    vlan_description: "ibgp vlan for vrf AZCD21-OUT"
    vrf: AVIATRIX-UNDERLAY
vpc_interfaces:
  Ethernet1:
    vpc_int_id: 1/53
    vpc_portchannel_id: 1
  Ethernet2:
    vpc_int_id: 1/54
    vpc_portchannel_id: 1
  Ethernet3:
    vpc_int_id: 1/25
    vpc_portchannel_id: 10
  Ethernet4:
    vpc_int_id: 1/26
    vpc_portchannel_id: 10
  Ethernet5:
    vpc_int_id: 1/27
    vpc_portchannel_id: 10
  Ethernet6:
    vpc_int_id: 1/28
    vpc_portchannel_id: 10
  Ethernet7:
    vpc_int_id: 1/13
    vpc_portchannel_id: 11
  Ethernet8:
    vpc_int_id: 1/14
    vpc_portchannel_id: 11
vpc_id:
  vpc_1:
    po_id: "1"
  vpc_10:
    po_id: "10"
  vpc_11:
    po_id: "11"
l3_interfaces:
  ethernet1/25:
    description: " l3 connection to NDCNBLVP04"
  ethernet1/26:
    description: " l3 connection to NDCNBLVP04"
  ethernet1/27:
    description: " l3 connection to NDCNBLVP04"
  ethernet1/28:
    description: " l3 connection to NDCNBLVP04"
  ethernet1/1:
    description: " l3 connection to PROD AVI-WAN"
  ethernet1/5:
    description: " l3 connection to PROD AVI-LAN"
  ethernet1/13:
    description: " l3 connection to NACNBLVP02"
  ethernet1/14:
    description: " l3 connection to NACNBLVP02"
  ethernet1/2:
    description: " l3 connection to PRE-PROD AVI-WAN"
  ethernet1/6:
    description: " l3 connection to PRE-PROD AVI-LAN"
l3_sub_interfaces:
  Po10.675:
    l3_sub_int_vrf: AVIATRIX-UNDERLAY
    l3_sub_int_ipv4: 10.137.80.121/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to NDCNBLVP04 VRF AVIATRIX-UNDERLAY"
  ethernet1/5.675:
    l3_sub_int_vrf: AZCD21
    l3_sub_int_ipv4: 10.137.82.101/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to AVI PROD LAN VRF AZCD21"
  ethernet1/5.676:
    l3_sub_int_vrf: AZCQ21
    l3_sub_int_ipv4: 10.137.82.109/30
    l3_sub_int_dot1q: 676
    l3_sub_description: "L3 sub-interface connection to AVI PROD LAN VRF AZCQ21"
  ethernet1/5.677:
    l3_sub_int_vrf: AZCP21
    l3_sub_int_ipv4: 10.137.82.117/30
    l3_sub_int_dot1q: 677
    l3_sub_description: "L3 sub-interface connection to AVI PROD LAN VRF AZCP21"
  Po11.675:
    l3_sub_int_vrf: AZCD21
    l3_sub_int_ipv4: 10.137.80.86/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to NDCNBCLVP02 VRF AZCD21"
  Po11.676:
    l3_sub_int_vrf: AZCQ21
    l3_sub_int_ipv4: 10.137.80.150/30
    l3_sub_int_dot1q: 676
    l3_sub_description: "L3 sub-interface connection to NDCNBCLVP02 VRF AZCQ21"
  Po11.677:
    l3_sub_int_vrf: AZCP21
    l3_sub_int_ipv4: 10.137.80.22/30
    l3_sub_int_dot1q: 677
    l3_sub_description: "L3 sub-interface connection to NDCNBCLVP02 VRF AZCP21"
  ethernet1/1.675:
    l3_sub_int_vrf: AVIATRIX-UNDERLAY
    l3_sub_int_ipv4: 10.137.82.105/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to AVI PROD WAN VRF AZCD21-OUT"
  ethernet1/2.675:
    l3_sub_int_vrf: AVIATRIX-UNDERLAY
    l3_sub_int_ipv4: 10.137.82.157/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD WAN VRF AZCD21-OUT"
  ethernet1/6.675:
    l3_sub_int_vrf: AZCD21
    l3_sub_int_ipv4: 10.137.82.153/30
    l3_sub_int_dot1q: 675
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD LAN VRF AZCD21-OUT"
  ethernet1/6.676:
    l3_sub_int_vrf: AZCQ21
    l3_sub_int_ipv4: 10.137.82.161/30
    l3_sub_int_dot1q: 676
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD LAN VRF AZCQ21-OUT"
  ethernet1/6.677:
    l3_sub_int_vrf: AZCP21
    l3_sub_int_ipv4: 10.137.82.169/30
    l3_sub_int_dot1q: 677
    l3_sub_description: "L3 sub-interface connection to AVI PREPROD LAN VRF AZCP21-OUT"
l3_bgp_neighbors:
  sw01_peer1:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.61
    bgp_vrf: AZCP21  
  sw01_peer2:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.189
    bgp_vrf: AZCQ21
  sw01_peer3:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.125
    bgp_vrf: AZCD21
  sw01_peer6:
    bgp_type: ibgp
    remote_asn: 65190
    remote_bgp_peer_ipv4: 10.137.80.241
    bgp_vrf: AVIATRIX-UNDERLAY
  vp04_peer2:
    bgp_type: ebgp
    remote_asn: 65189
    remote_bgp_peer_ipv4: 10.137.80.122
    bgp_vrf: AVIATRIX-UNDERLAY
  vp02_peer1:
    bgp_type: ebgp
    remote_asn: 65206
    remote_bgp_peer_ipv4: 10.137.80.21
    bgp_vrf: AZCP21 
  vp02_peer2:
    bgp_type: ebgp
    remote_asn: 65206
    remote_bgp_peer_ipv4: 10.137.80.85
    bgp_vrf: AZCD21 
  vp02_peer3:
    bgp_type: ebgp
    remote_asn: 65206
    remote_bgp_peer_ipv4: 10.137.80.149
    bgp_vrf: AZCQ21
  av1prod_peer1:
    bgp_type: ebgp
    remote_asn: 64523
    remote_bgp_peer_ipv4: 10.137.82.102
    bgp_vrf: AZCD21
  av1prod_peer2:
    bgp_type: ebgp
    remote_asn: 64522
    remote_bgp_peer_ipv4: 10.137.82.110
    bgp_vrf: AZCQ21 
  av1prod_peer3:
    bgp_type: ebgp
    remote_asn: 64521
    remote_bgp_peer_ipv4: 10.137.82.118
    bgp_vrf: AZCP21
  avipre_prod_peer1:
    bgp_type: ebgp
    remote_asn: 64523
    remote_bgp_peer_ipv4: 10.137.82.154
    bgp_vrf: AZCD21
  avipre_prod_peer2:
    bgp_type: ebgp
    remote_asn: 64522
    remote_bgp_peer_ipv4: 10.137.82.162
    bgp_vrf: AZCQ21 
  avipre_prod_peer3:
    bgp_type: ebgp
    remote_asn: 64521
    remote_bgp_peer_ipv4: 10.137.82.170 
    bgp_vrf: AZCP21
redis_connected:
  ethernet1/1.675:
    vrf: AVIATRIX-UNDERLAY
  ethernet1/2.675:
    vrf: AVIATRIX-UNDERLAY